### ISSUE TITLE
Windows, init-db error

### ISSUE THREAD

**Issue by auto-septik** [long2ice/aerich#16]
Python 3.8
Log:
(discord-bot) C:\Users\niksonbinsk\PycharmProjects\discord-bot>aerich init-db
c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\box\box.py:928: BoxWarning: msgpack is not found in the environment. `to_msgpack` and `from_msgpack` transforms will not work
  warnings.warn(
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\niksonbinsk\.virtualenvs\discord-bot-cMd0c8iy\Scripts\aerich.exe\__main__.py", line 7, in <module>
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\cli.py", line 231, in main
    cli(_anyio_backend="asyncio")
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\_backends\_asyncio.py", line 99, in run
    raise exception
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\_backends\_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 1175, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 588, in invoke
    rv = await rv
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\cli.py", line 206, in init_db
    os.mkdir(dirname)
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'migrations\\models'

(discord-bot) C:\Users\niksonbinsk\PycharmProjects\discord-bot>aerich init-db
c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\box\box.py:928: BoxWarning: msgpack is not found in the environment. `to_msgpack` and `from_msgpack` transforms will not work
  warnings.warn(
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\niksonbinsk\.virtualenvs\discord-bot-cMd0c8iy\Scripts\aerich.exe\__main__.py", line 7, in <module>
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\cli.py", line 231, in main
    cli(_anyio_backend="asyncio")
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\_backends\_asyncio.py", line 99, in run
    raise exception
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\_backends\_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 1175, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 588, in invoke
    rv = await rv
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\cli.py", line 206, in init_db
    os.mkdir(dirname)
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: './migrations\\models'

(discord-bot) C:\Users\niksonbinsk\PycharmProjects\discord-bot>aerich init -t models.config
Success create migrate location ./migrations
Success generate config file aerich.ini

(discord-bot) C:\Users\niksonbinsk\PycharmProjects\discord-bot>aerich init-db
c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\box\box.py:928: BoxWarning: msgpack is not found in the environment. `to_msgpack` and `from_msgpack` transforms will not work
  warnings.warn(
Success create app migrate location ./migrations\models
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\niksonbinsk\.virtualenvs\discord-bot-cMd0c8iy\Scripts\aerich.exe\__main__.py", line 7, in <module>
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\cli.py", line 231, in main
    cli(_anyio_backend="asyncio")
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\_backends\_asyncio.py", line 99, in run
    raise exception
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\anyio\_backends\_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 1175, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\asyncclick\core.py", line 588, in invoke
    rv = await rv
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\cli.py", line 211, in init_db
    Migrate.write_old_models(config, app, location)
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\migrate.py", line 198, in write_old_models
    cls.cp_models(app, old_model_files, os.path.join(location, app, cls.get_old_model_file()))
  File "c:\users\niksonbinsk\.virtualenvs\discord-bot-cmd0c8iy\lib\site-packages\aerich\migrate.py", line 158, in cp_models
    content = f.read()
  File "c:\program files\python38\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 844: character maps to <undefined>

aerich.ini: 

[aerich]
tortoise_orm = models.config
location = ./migrations
`

**Comment by long2ice** [comment]
Maybe you should install `msgpack` first.

**Comment by auto-septik** [comment]
Fixed with 0.2.1 update
