### ISSUE TITLE
Failed to build dockerfile

### ISSUE THREAD

**Issue by auto-septik** [long2ice/aerich#17]
OS: Ubuntu 19.04
Log:
```
Step 8/11 : RUN poetry run aerich migrate

---> Running in 71227fb4ebdb
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/tortoise/__init__.py", line 353, in _discover_models
    module = importlib.import_module(models_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'migrations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/bin/aerich", line 11, in <module>
    load_entry_point('aerich', 'console_scripts', 'aerich')()
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/src/aerich/aerich/cli.py", line 231, in main
    cli(_anyio_backend="asyncio")
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/anyio/__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 99, in run
    raise exception
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/asyncclick/core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/asyncclick/core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/asyncclick/core.py", line 1172, in invoke
    await Command.invoke(self, ctx)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/asyncclick/core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/asyncclick/core.py", line 588, in invoke
    rv = await rv
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/src/aerich/aerich/cli.py", line 67, in cli
    await Migrate.init_with_old_models(tortoise_config, app, location)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/src/aerich/aerich/migrate.py", line 60, in init_with_old_models
    await Tortoise.init(config=migrate_config)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/tortoise/__init__.py", line 556, in init
    cls._init_apps(apps_config)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/tortoise/__init__.py", line 425, in _init_apps
    cls.init_models(info["models"], name, _init_relations=False)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/tortoise/__init__.py", line 406, in init_models
    app_models += cls._discover_models(module, app_label)
  File "/root/.cache/pypoetry/virtualenvs/root-bot-VA82Wl8V-py3.8/lib/python3.8/site-packages/tortoise/__init__.py", line 355, in _discover_models
    raise ConfigurationError(f'Module "{models_path}" not found')
tortoise.exceptions.ConfigurationError: Module "migrations.models.old_models" not found

{"code":1,"message":"The command '/bin/sh -c poetry run aerich migrate' returned a non-zero code: 1"}
The command '/bin/sh -c poetry run aerich migrate' returned a non-zero code: 1
Build has failed!
----------------------
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c poetry run aerich migrate' returned a non-zero code: 1"}
The command '/bin/sh -c poetry run aerich migrate' returned a non-zero code: 1

```
Dockerfile:
  ```
                      "FROM python:3.8.3",
                        "RUN apt update",
                        "RUN apt install liblua5.2-dev ffmpeg -y",
                        "RUN pip3 install poetry",
                        "COPY ./ /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "RUN poetry install",
                        "RUN poetry run aerich migrate",
                        "RUN poetry run aerich upgrade",
                        "ENV ENV_FOR_DYNACONF production",
                        "RUN poetry run python3 bot.py"
```

ini file:
```
[aerich]
tortoise_orm = models.config
location = ./migrations
```

_Used dev branch_

**Comment by auto-septik** [comment]
On windows all is ok

**Comment by long2ice** [comment]
I'm not use aerich as that, maybe you can install it in container as requirement and exec `aerich upgrade` in it, but not in Dockerfile.

**Comment by auto-septik** [comment]
> I'm not use aerich as that, maybe you can install it in container as requirement and exec `aerich upgrade` in it, but not in Dockerfile.

It's not possible due to limitations of CapRover

Anyway, problem solved
