### ISSUE TITLE
custom SSL Cert. aerich upgrade. TypeError: can't pickle SSLContext objects

### ISSUE THREAD

**Issue by maxim-s-barabash** [long2ice/aerich#33]
aerich v 0.2.2

My database requires ssl. I have a connection configuration according to the documentation 
https://tortoise-orm.readthedocs.io/en/latest/databases.html#db-ssl

This is how my config looks like
```
print(config)
{'connections': {
   'default': {
        'engine': 'tortoise.backends.asyncpg', 'minsize': 1, 'maxsize': 3, 
        'credentials': {
             'database': 'testdb', 
            'host': 'db-postgresql', 
            'password': '*****', 'port': 25061, 'user': 'testuser', 
            'ssl': <ssl.SSLContext object at 0x7f883c857520>
        }
     }
   }, 
  'apps': {
    'models': {
        'models': ['my.model', 'aerich.models']
      }
  }
}
```

`aerich upgrade` gives an error message
```sh
aerich upgrade
Traceback (most recent call last):
  File "/usr/local/bin/aerich", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/aerich/cli.py", line 231, in main
    cli(_anyio_backend="asyncio")
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/usr/local/lib/python3.7/dist-packages/anyio/__init__.py", line 72, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 114, in run
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 76, in wrapper
    retval = await func(*args)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 1172, in invoke
    await Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/asyncclick/core.py", line 588, in invoke
    rv = await rv
  File "/usr/local/lib/python3.7/dist-packages/aerich/cli.py", line 67, in cli
    await Migrate.init_with_old_models(tortoise_config, app, location)
  File "/usr/local/lib/python3.7/dist-packages/aerich/migrate.py", line 55, in init_with_old_models
    migrate_config = cls._get_migrate_config(config, app, location)
  File "/usr/local/lib/python3.7/dist-packages/aerich/migrate.py", line 175, in _get_migrate_config
    temp_config = deepcopy(config)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle SSLContext objects
```

**Comment by long2ice** [comment]
You can update from dev branch and give it a try.

**Comment by maxim-s-barabash** [comment]
It works for me. Thank.
