### ISSUE TITLE
tortoise.exceptions.ConfigurationError: Unknown connection "default" for app "diff_models"

### ISSUE THREAD

**Issue by codefather-labs** [long2ice/aerich#6]
```
database_config = {
    "connections": {
        Database.telegram.name: Database.telegram.value
    },
    "apps": {
        "telegram": {
            "models": models,
            "default_connection": Database.telegram.name
        },
    },
}
```
[Mon May 25 18:20:25 2020]: Executing step 1
Success create migrate location ./migrations
Success generate config file aerich.ini

[Mon May 25 18:20:25 2020]: Executing step 2
Success create app migrate location ./migrations/telegram
Success generate schema for app "telegram"

[Mon May 25 18:20:26 2020]: Executing step 3

> docker exec -it telegramcms.services aerich migrate --name drop_column
> docker exec -it telegramcms.services aerich upgrade

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tortoise/__init__.py", line 417, in _init_apps
    cls.get_connection(info.get("default_connection", "default"))
  File "/usr/local/lib/python3.8/dist-packages/tortoise/__init__.py", line 45, in get_connection
    return cls._connections[connection_name]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aerich", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/aerich/cli.py", line 224, in main
    cli(_anyio_backend="asyncio")
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/usr/local/lib/python3.8/dist-packages/anyio/__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 97, in run
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 1172, in invoke
    await Command.invoke(self, ctx)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 588, in invoke
    rv = await rv
  File "/usr/local/lib/python3.8/dist-packages/aerich/cli.py", line 64, in cli
    await Migrate.init_with_old_models(tortoise_config, app, location)
  File "/usr/local/lib/python3.8/dist-packages/aerich/migrate.py", line 59, in init_with_old_models
    await Tortoise.init(config=migrate_config)
  File "/usr/local/lib/python3.8/dist-packages/tortoise/__init__.py", line 556, in init
    cls._init_apps(apps_config)
  File "/usr/local/lib/python3.8/dist-packages/tortoise/__init__.py", line 419, in _init_apps
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: Unknown connection "default" for app "diff_models"

**Comment by codefather-labs** [comment]
My model metaclass example:

```
class Meta:
   table = 'TelegramApplication'
   default_connection = Database.telegram.name
```

**Comment by codefather-labs** [comment]
```
class Database(Enum):
    telegram = "postgres://{}:{}@{}:{}/{}".format(
        os.environ.get("DB_USER"),
        os.environ.get("DB_PASS"),
        os.environ.get("DB_HOST"),
        os.environ.get("DB_PORT"),
        os.environ.get("DB_NAME")
    )

```

**Comment by long2ice** [comment]
OK, I fixed in [https://github.com/long2ice/aerich/commit/881f70f74881133c236b234a7bf52825f47f2a86](https://github.com/long2ice/aerich/commit/881f70f74881133c236b234a7bf52825f47f2a86), you can install from github and give it a try.

**Comment by long2ice** [comment]
Just run ``pip install -e git+https://github.com/long2ice/aerich.git@dev#egg=aerich``

**Comment by codefather-labs** [comment]
still got `tortoise.exceptions.ConfigurationError: Unknown connection "default" for app "diff_models"`

**Comment by codefather-labs** [comment]
aerich, version 0.1.9

`aerich migrate`

Traceback (most recent call last):
  File "/usr/local/bin/aerich", line 11, in <module>
    load_entry_point('aerich', 'console_scripts', 'aerich')()
  File "/app/src/aerich/aerich/cli.py", line 229, in main
    cli(_anyio_backend="asyncio")
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/usr/local/lib/python3.8/dist-packages/anyio/__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 97, in run
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 1172, in invoke
    await Command.invoke(self, ctx)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/asyncclick/core.py", line 588, in invoke
    rv = await rv
  File "/app/src/aerich/aerich/cli.py", line 65, in cli
    await Migrate.init_with_old_models(tortoise_config, app, location)
  File "/app/src/aerich/aerich/migrate.py", line 53, in init_with_old_models
    migrate_config = cls._get_migrate_config(config, app, location)
  File "/app/src/aerich/aerich/migrate.py", line 179, in _get_migrate_config
    "default_connection": config.get("apps").get(app).get("default_connection","default"),
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by codefather-labs** [comment]
i can show my code repo

https://bitbucket.org/codefather-hub/telegram-cms/src/master/docker/services/Dockerfile
https://bitbucket.org/codefather-hub/telegram-cms/src/master/docker/tools/migrate.py

https://bitbucket.org/codefather-hub/telegram-cms/src/master/services/core/models.py
https://bitbucket.org/codefather-hub/telegram-cms/src/master/services/feed/models.py
https://bitbucket.org/codefather-hub/telegram-cms/src/master/services/telegram/models.py

**Comment by codefather-labs** [comment]
it can connect to connection wich not named 'default'?

**Comment by long2ice** [comment]
You must specify ``--app=telegram``

**Comment by codefather-labs** [comment]
finally dev branch works for me

**Comment by codefather-labs** [comment]
```
RUN mkdir vendor && cd vendor && git clone -b dev https://github.com/long2ice/aerich.git && \
    cd aerich && python3.8 setup.py install
RUN rm -rf vendor

RUN aerich --version
```

**Comment by long2ice** [comment]
OK, nice to hear that.
